#!/usr/bin/env bash
set -euo pipefail

CFG_FILE="${1:-Config.mk}"

fb=1
mouse=1
fs=1
recovery=1
text=1

if [[ -f "$CFG_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$CFG_FILE"
  fb=${CONFIG_FB:-1}
  mouse=${CONFIG_MOUSE:-1}
  fs=${CONFIG_FS:-1}
  recovery=${CONFIG_RECOVERY:-1}
  text=${CONFIG_TEXT:-1}
fi

toggle() {
  local v="$1"
  if [[ "$v" == "1" ]]; then echo 0; else echo 1; fi
}

while true; do
  clear
  echo "=== MyCoreOS menuconfig ==="
  echo
  echo "1) Framebuffer support      : $fb"
  echo "2) PS/2 mouse support       : $mouse"
  echo "3) Filesystem layer         : $fs"
  echo "4) Recovery mode            : $recovery"
  echo "5) Text overlay             : $text"
  echo
  echo "s) Save and exit"
  echo "q) Quit without saving"
  echo
  read -rp "Select option: " choice
  case "$choice" in
    1) fb=$(toggle "$fb") ;;
    2) mouse=$(toggle "$mouse") ;;
    3) fs=$(toggle "$fs") ;;
    4) recovery=$(toggle "$recovery") ;;
    5) text=$(toggle "$text") ;;
    s|S)
      cat > "$CFG_FILE" <<CFG
# Auto-generated by menuconfig
CONFIG_FB := $fb
CONFIG_MOUSE := $mouse
CONFIG_FS := $fs
CONFIG_RECOVERY := $recovery
CONFIG_TEXT := $text
CFG
      echo "Saved $CFG_FILE"
      exit 0
      ;;
    q|Q) exit 0 ;;
  esac
done
